POST http://localhost:3001/api/persons
Content-Type: application/json

{
        "id": 1,
      "name": "Arsdws", 
      "number": "04we23456"
}


###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
        "id": 1,
      "name": "Arto Hellas", 
      "number": ""
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
        "id": 1,
      "name": "Arto Hellas", 
      "number": ""
}
